### ISSUE TITLE
invalid_client error

### ISSUE THREAD

**Issue by Pacando** [klarna/flutter-klarna-inapp-sdk#26]
I'm getting an invalid_client error (client credentials are not valid) in the webview after **authorizationRequest** is invoked.
<img width="346" alt="Screenshot 2021-03-08 at 10 47 30 PM" src="https://user-images.githubusercontent.com/80915970/111673887-6db8a000-8841-11eb-9d79-435d829f9513.png">
Where can I get the client credentials? (clientId and operationToken)

**Comment by omarbh** [comment]
HI @Pacando,
I think you are missing the credentials please see this page https://developers.klarna.com/documentation/checklist/developer/ on how to get them.
Cheers

**Comment by Pacando** [comment]
I have a playground account. Am I supposed to use Klarna API Credentials for client credentials?
<img width="777" alt="Screenshot 2021-03-09 at 9 18 29 AM" src="https://user-images.githubusercontent.com/80915970/111767604-ef094480-88cc-11eb-8b60-685a4ddbcda3.png">

**Comment by omarbh** [comment]
sorry for the confusion, the link shared above is for the payment credentials and not for the post-purchase api (the flutter plugin does not support yet the payment api).  To get the cedentails for the post-purchase API the merchant needs to reach out to the technical solution engineer contact from the Klarna side and they will able to help out.

**Comment by Pacando** [comment]
I contacted Klarna regarding this. According to them the Klarna API Credentials are the same for payment and post-purchase API. I am already using those credentials for the example. I still am getting an invalid_client error.

<img width="500" alt="Screenshot 2021-03-27 at 11 32 55 PM" src="https://user-images.githubusercontent.com/80915970/112729969-db0cb500-8f54-11eb-98fb-dc38b9a91248.png">

I'm using Username(UID) as **clientToken** and Password as **operationToken**
Am I using them incorrectly?

**Comment by omarbh** [comment]
These credentials will not work for the post purchase api, can you reach out to mikhail.romanov@klarna.com and provide information about your case, merchant name and  the Klarna account manger associated to your merchant.

**Comment by omarbh** [comment]
Hi @Pacando I will close the ticket and feel free to open it if you still need help. We will update our read me file on how to get the post purchase credentials
