### ISSUE TITLE
Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler.

### ISSUE THREAD

**Issue by sebboseb** [klarna/flutter-klarna-inapp-sdk#27]
Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler

**Comment by omarbh** [comment]
HI @sebastianmarzjan can you provide more information about the issue by following this guideline here : https://github.com/klarna/flutter-klarna-inapp-sdk/issues/27

**Comment by sebastianmarzjan** [comment]
@omarbh I think you tagged the wrong person :-)

**Comment by omarbh** [comment]
closing this issue, please feel free to open it again if you still have the issue.
